### ISSUE TITLE
Add PrivateAssets="All" to any weaver package WinUI 3 packaged app will fail to build.

### ISSUE THREAD

**Issue by lighterhy** [Fody/Fody#1093]
Add PrivateAssets="All" to any weaver package in **WinUI 3 packaged app** will fail to build with following error:

```
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): error APPX1101: Payload contains two or more files with the same destination path 'App1.deps.json'. Source files: 
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): error APPX1101: C:\Projects\App1\App1\obj\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\App1.deps.json
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): error APPX1101: C:\Projects\App1\App1\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\App1.deps.json
```

After that, **all the projects that reference "Microsoft.WindowsAppSDK" will fail to build** with following error:

```
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018: The "ExpandPriContent" task failed unexpectedly.
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018: System.ObjectDisposedException: Cannot access a disposed object.
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018: Object name: 'it is not allowed to use disposed Microsoft.VisualStudio.Telemetry.TelemetrySession object.'.
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.VisualStudio.Telemetry.TelemetryDisposableObject.RequiresNotDisposed()
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.VisualStudio.Telemetry.TelemetrySession.SerializeSettings()
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.Build.AppxPackage.Telemetry.Get(IBuildEngine4 buildEngine, String vsTelemetrySession)
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskHelper..ctor(IBuildEngine4 buildEngine, TaskLoggingHelper logger, Action execute, Func`2 exceptionHandler, Action cleanup, Func`1 manifestFileNameGetter, String vsTelemetrySession)
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingToolTaskBase.Execute()
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\lighterz\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\MrtCore.PriGen.targets(891,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

This error will never gone until I restarting Visual Studio.
My environment is Visual Studio 17.2 preview 5 with .NET 6 preview.

This issue does not occurs on WinUI 3 app with Windows Application Packaging Project.

[App1.zip](https://github.com/Fody/Fody/files/8579677/App1.zip)

**Comment by SimonCropp** [comment]
looks like you should raise a bug with VisualStudio.Telemetry

**Comment by lighterhy** [comment]
> looks like you should raise a bug with VisualStudio.Telemetry

I don't know how this is caused, But when I remove PrivateAssets="All" and restart Visual Studio, The problem is gone.
