### ISSUE TITLE
FileNotFoundException when trying to use a type from another assemblu

### ISSUE THREAD

**Issue by mrpmorris** [Fody/Fody#1164]
#### Describe the issue

When my weaver includes the code `typeof(MinLengthAttribute)`, I get an exception at weaving time.

```
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Failed to execute weaver C:\Users\X\source\repos\ConsoleApp88\Moxy.Fody\bin\Debug\netstandard2.0\Moxy.Fody.dll
2>MSBUILD : error : Type:
2>MSBUILD : error : System.Exception
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 222
2>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 113
2>MSBUILD : error : Source:
2>MSBUILD : error : FodyIsolated
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void ExecuteWeavers()
2>MSBUILD : error : Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2>MSBUILD : error : Type:
2>MSBUILD : error : System.IO.FileNotFoundException
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at Moxy.Fody.ModuleWeaver.<>c.<ScanProperty>b__3_0(CustomAttribute a)
2>MSBUILD : error :    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2>MSBUILD : error :    at Moxy.Fody.ModuleWeaver.ScanProperty(TypeDefinition type, PropertyDefinition property)
2>MSBUILD : error :    at Moxy.Fody.ModuleWeaver.ScanType(TypeDefinition type)
2>MSBUILD : error :    at Moxy.Fody.ModuleWeaver.Execute()
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 186
2>MSBUILD : error : Source:
2>MSBUILD : error : Moxy.Fody
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Boolean <ScanProperty>b__3_0(Mono.Cecil.CustomAttribute)
```

#### Minimal Repro

Repro [here](https://github.com/mrpmorris/Moxy.Fody)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FodyHelpers" Version="6.6.4" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.1.0" />
  </ItemGroup>

</Project>
```

```
using Fody;
using Mono.Cecil;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace Moxy.Fody
{
	public class ModuleWeaver : BaseModuleWeaver
	{
		public override IEnumerable<string> GetAssembliesForScanning()
		{
			yield return "netstandard";
			yield return "mscorlib";
		}

		public override void Execute()
		{
			foreach (var type in ModuleDefinition.Types)
			{
				ScanType(type);
			}
		}

		private void ScanType(TypeDefinition type)
		{
			foreach (var property in type.Properties)
			{
				ScanProperty(type, property);
			}
		}

		private void ScanProperty(TypeDefinition type, PropertyDefinition property)
		{
			var minLengthAttribute = property.CustomAttributes.FirstOrDefault(a => a.AttributeType.FullName == typeof(MinLengthAttribute).FullName);

			if (minLengthAttribute != null)
			{
				WriteMessage($"{type.FullName}.{property.Name}", MessageImportance.High);
			}
		}
	}
}
```

**Comment by tom-englert** [comment]
https://github.com/Fody/Home/blob/master/pages/addin-development.md

Should not have any runtime dependencies (excluding Mono Cecil); runtime dependencies should be combined using e.g. ILMerge and the /Internalize flag.

**Comment by tom-englert** [comment]
In your use case you must not compute the type name at runtime (`typeof(MinLengthAttribute).FullName`), but provide it as a const string, this is what all other weavers do.
