### ISSUE TITLE
The "Fody.WeavingTask" task failed unexpectedly: The type initializer for 'ContainsTypeChecker' threw an exception

### ISSUE THREAD

**Issue by dmitrygrig** [Fody/Fody#124]
Hello, Simon 

I've got today very similar exception to this one (https://github.com/Fody/Fody/issues/87) trying to build Virtuosity project (I should say that I get the same error for all Fody projects):

```
Error   2   The "Fody.WeavingTask" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.NotSupportedException: '#' character in path is not supported while building projects containing Fody.
   at AssemblyLocation.CurrentDirectory() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\AssemblyLocation.cs:line 13
   at ContainsTypeChecker..cctor() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\ContainsTypeChecker.cs:line 9
   --- End of inner exception stack trace ---
   at ContainsTypeChecker..ctor()
   at Processor..ctor() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\Processor.cs:line 28
   at Fody.WeavingTask.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\WeavingTask.cs:line 44
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() Fody
```

I didn't get a hint from #87 how to resolve an issue, therefore I would be very grateful to you for your help. 

Thank you in advance.

Regards,
Dmitry

**Comment by canton7** [comment]
For anyone else stumbling on this, I had a similar issue:

```
Error           The "Fody.WeavingTask" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///<path>\packages\Fody.1.29.2\FodyIsolated.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
```

The solution is to right-click the dll in question, and check the 'Unblock' checkmark.

**Comment by SimonCropp** [comment]
@canton7 that is interesting. did u do your install using nuget?

**Comment by canton7** [comment]
I did, but I zipped up the project (including `packages`) and sent it to someone else, who hit the error.

**Comment by SimonCropp** [comment]
ahh. yeah the trick is to delete the packages dir before creating the zip. then nuget will restore them

**Comment by canton7** [comment]
Yep, I was trying to be nice, heh. The .NET error doesn't make it obvious what the problem is, so thought I'd share in case anyone else was googling and hit this issue.
