### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by naveensrinivasan** [Fody/Fody#171]
I am running into an exception 
```
Severity	Code	Description	Project	File	Line
Error		Fody: An unhandled exception occurred:
Exception:
Unknown custom metadata item kind: 6
StackTrace:
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\ModuleReader.cs:line 14
   at InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\InnerWeaver.cs:line 28
Source:
Mono.Cecil.Pdb
TargetSite:
Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)	ManagedCallStack		
```
I am using VS2015.

**Comment by SimonCropp** [comment]
what version of fody?

**Comment by naveensrinivasan** [comment]
Here is the version info
```
  <package id="Costura.Fody" version="1.3.3.0" targetFramework="net45" />
  <package id="Fody" version="1.26.1" targetFramework="net45" developmentDependency="true" />
```

**Comment by SimonCropp** [comment]
please try 1.28.3

**Comment by GeertvanHorrik** [comment]
I have this issue as well, just wanted to create it. It happens in VS 2015 RC. But I use it on a *lot* of projects, just got this on a newly created project.

**Comment by GeertvanHorrik** [comment]
I am pretty sure I check for updates very often, somehow it doesn't pick a version higher than 1.26.1. Crappy Nuget....

**Comment by GeertvanHorrik** [comment]
See https://github.com/NuGet/Home/issues/615, you must manually update:

```
Update-Package Fody
```

**Comment by GeertvanHorrik** [comment]
After updating, the exception is gonel.

**Comment by SimonCropp** [comment]
Sorry to hear about the hassle

**Comment by SimonCropp** [comment]
Closing this one since the fix is simple. Well would be if nuget wasnt broken :)

**Comment by GeertvanHorrik** [comment]
It's not your fault, so don't worry about it. I already reported it at NuGet, but this is fixed.

**Comment by naveensrinivasan** [comment]
@GeertvanHorrik Thanks for update!
