### ISSUE TITLE
Unhandled exception when weaving iOS with 1.29

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/Fody#186]
Just upgraded from 1.28.3 to 1.29, and I got this:

```
6>MSBUILD : error : Fody: An unhandled exception occurred:
6>MSBUILD : error : Exception:
6>MSBUILD : error : Failed to compare two elements in the array.
6>MSBUILD : error : StackTrace:
6>MSBUILD : error :    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
6>MSBUILD : error :    at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
6>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.AddGenericParameters()
6>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildTypes()
6>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.BuildModule()
6>MSBUILD : error :    at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
6>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
6>MSBUILD : error :    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
6>MSBUILD : error :    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
6>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
6>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
6>MSBUILD : error :    at InnerWeaver.WriteModule() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\ModuleWriter.cs:line 18
6>MSBUILD : error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 85
6>MSBUILD : error : Source:
6>MSBUILD : error : mscorlib
6>MSBUILD : error : TargetSite:
6>MSBUILD : error : Void Sort(T[], Int32, Int32, System.Collections.Generic.IComparer`1[T])
6>MSBUILD : error : Value does not fall within the expected range.
6>MSBUILD : error : StackTrace:
6>MSBUILD : error :    at Mono.Cecil.Mixin.CompressMetadataToken(CodedIndex self, MetadataToken token)
6>MSBUILD : error :    at Mono.Cecil.MetadataBuilder.GenericParameterComparer.Compare(GenericParameter a, GenericParameter b)
6>MSBUILD : error :    at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
6>MSBUILD : error :    at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
6>MSBUILD : error :    at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
6>MSBUILD : error :    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
6>MSBUILD : error : Source:
6>MSBUILD : error : Mono.Cecil
6>MSBUILD : error : TargetSite:
6>MSBUILD : error : UInt32 CompressMetadataToken(Mono.Cecil.Metadata.CodedIndex, Mono.Cecil.MetadataToken)
6>MSBUILD : error : 
```

**Comment by GeertvanHorrik** [comment]
Might be a weaver, will put investigation stuff here.

**Comment by SimonCropp** [comment]
source/dll that caused the error?

**Comment by GeertvanHorrik** [comment]
This happens to Catel.Core.iOS. But making sure it's not me. I updated both Catel.Fody and Fody, so need to be sure it's not me.

**Comment by GeertvanHorrik** [comment]
All other projects work (NET40 / NET45 / NET46 / WIN81 / WP80 / WP80 (SL) / WP80 (RT) / Xamarin.Android / PCL).

**Comment by GeertvanHorrik** [comment]
And magically, after restarting VS, even iOS works.

**Comment by GeertvanHorrik** [comment]
Sorry for the inconvenience

**Comment by GeertvanHorrik** [comment]
Just restarted my machine, now this pops up in multiple projects.

**Comment by GeertvanHorrik** [comment]
But always Catel.Core. Might be my weaver running against Catel.Core trying to use Catel.Core methods.

**Comment by SimonCropp** [comment]
so if i build catel on 2015 i should get the error? do i need xamarin bits installed?

**Comment by GeertvanHorrik** [comment]
Not sure. Please don't spend time on this until I am absolutely sure what the cause is. I don't want to waste your precious time.

**Comment by SimonCropp** [comment]
lol. if i can get a repro it is not a waste of time.

**Comment by GeertvanHorrik** [comment]
But even I can't repro it consistently. Sometimes it happens, sometimes it doesn't. I am sure I killed off all msbuild, and am using VS 2015 RC for months now. Things I have changed:

1. Updated Fody to 1.29
2. Updated to VS 2015 RTM

More stuff broke (like some unit tests (valid) and PE verification) after roslyn kicked in (but why didn't it in RC?). Still investigating.
