### ISSUE TITLE
Exception with VB Project and StrongNameKeyPair

### ISSUE THREAD

**Issue by NeilMJohnson** [Fody/Fody#243]
I added the Fody.PropertyChanged extension and added the ImplementPropertyChanged attribute on two of my Entity Framework classes and tried to compile them and got the following exception:

```
Error 1 Fody: An unhandled exception occurred:
Exception:
Unable to obtain public key for StrongNameKeyPair.
StackTrace:
at System.Reflection.StrongNameKeyPair.ComputePublicKey()
at System.Reflection.StrongNameKeyPair.get_PublicKey()
at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
at InnerWeaver.WriteModule() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\ModuleWriter.cs:line 18
at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 85
Source:
mscorlib
TargetSite:
Byte[] ComputePublicKey()
DataModels

```

I am using VS2010 with Visual Basic.

The project does have a StrongNameKey associated with it in a .pfx file. All of the projects in the solution have StrongNameKeys so I cannot remove the key from this project. Am I missing something in the configuration for this add-on? All of the projects have compiled fine with the StrongNameKeyPair with no problems up until this point.  The project file has the correct lines in it for the assembly signing:

```
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>Armada.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>

```

The Armada.pfx file is also in the project directory.  Any suggestions?

Thanks, Neil

**Comment by SimonCropp** [comment]
i think the problem might be that the key is password protected. can u try with a snk

**Comment by SimonCropp** [comment]
let me know if u get it working with an snk
