### ISSUE TITLE
vc 17

### ISSUE THREAD

**Issue by Kn1fe** [Fody/Fody#283]
When im try compile project:

`Fody: An unhandled exception occurred:
Exception:
Value cannot be null.
Parameter name: method
StackTrace:
   at Mono.Cecil.ModuleDefinition.ImportReference(MethodReference method, IGenericParameterProvider context)
   at ModuleWeaver.Import(Object operand) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 277
   at ModuleWeaver.CloneInstruction(Instruction instruction) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 227
   at ModuleWeaver.CopyInstructions(MethodDefinition templateMethod, MethodDefinition newMethod) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 212
   at ModuleWeaver.CopyMethod(MethodDefinition templateMethod, Boolean makePrivate) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 157
   at ModuleWeaver.ImportAssemblyLoader(Boolean createTemporaryAssemblies) in C:\projects\costura\src\Costura\AssemblyLoaderImporter.cs:line 52
   at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 38
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.MethodReference ImportReference(Mono.Cecil.MethodReference, Mono.Cecil.IGenericParameterProvider)	CompliteMiniEditors	`

Fody 1.30.0-beta01
Costura 2.0.0-beta0018

**Comment by Kn1fe** [comment]
So, when im downgrade costura to 1.3.3, it worked
