### ISSUE TITLE
Unsupported target framework: WindowsPhoneApp,Version=v8.1

### ISSUE THREAD

**Issue by boodoolak** [Fody/Fody#293]
Hi, I want use Realm on WP8.1, but app building not success.
How fix or workaround it?
```Error		Fody: An unhandled exception occurred:
Exception:
Unsupported target framework: WindowsPhoneApp,Version=v8.1
StackTrace:
   at RealmWeaver.ImportedReferences.Create(ModuleDefinition module)
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
RealmWeaver.Fody
TargetSite:
RealmWeaver.ImportedReferences Create(Mono.Cecil.ModuleDefinition)	wp81

**Comment by SimonCropp** [comment]
isnt windows phone dead?

**Comment by boodoolak** [comment]
Support wp8.1 is business requirement for my app.

**Comment by SimonCropp** [comment]
and what weavers do you intend to use?

**Comment by boodoolak** [comment]
ReactiveUI, RealmWeaver(?)

**Comment by SimonCropp** [comment]
actually looking at the stack trace this is a bug with Realm. can u raise an issue with them
