### ISSUE TITLE
ArgumentException after upgrade from 1.29.4 to 2.0.6

### ISSUE THREAD

**Issue by lu8848** [Fody/Fody#321]
How to know exactly where it is from, but my code worked fine with Fody 1.29.4 before.

System.ArgumentException: Value does not fall within the expected range..

    at Mono.Cecil.Pdb.ISymUnmanagedWriter2.DefineLocalVariable2(String name, Int32 attributes, Int32 sigToken, Int32 addrKind, Int32 addr1, Int32 addr2, Int32 addr3, Int32 startOffset, Int32 endOffset)
   at Mono.Cecil.Pdb.SymWriter.DefineLocalVariable2(String name, VariableAttributes attributes, Int32 sigToken, Int32 addr1, Int32 addr2, Int32 addr3, Int32 startOffset, Int32 endOffset) in C:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\SymWriter.cs:line 68
   at Mono.Cecil.Pdb.NativePdbWriter.DefineLocalVariable(VariableDebugInformation variable, Int32 local_var_token, Int32 start_offset, Int32 end_offset) in C:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\NativePdbWriter.cs:line 222
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent) in C:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\NativePdbWriter.cs:line 184
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent) in C:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\NativePdbWriter.cs:line 198
   at Mono.Cecil.Pdb.NativePdbWriter.Write(MethodDebugInformation info) in C:\Code\cecil\symbols\pdb\Mono.Cecil.Pdb\NativePdbWriter.cs:line 71
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method) in C:\Code\cecil\Mono.Cecil.Cil\CodeWriter.cs:line 136
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method) in C:\Code\cecil\Mono.Cecil.Cil\CodeWriter.cs:line 56
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1627
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1620
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1441
   at Mono.Cecil.MetadataBuilder.AddTypes() in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1413
   at Mono.Cecil.MetadataBuilder.BuildTypes() in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1266
   at Mono.Cecil.MetadataBuilder.BuildModule() in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1034
   at Mono.Cecil.MetadataBuilder.BuildMetadata() in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 1004
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__1_0(MetadataBuilder builder, MetadataReader _) in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 137
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) in C:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 936
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 136
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 111
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in C:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 1123

**Comment by SimonCropp** [comment]
Can u share a solution that reproduces this exception

**Comment by SimonCropp** [comment]
let me know if u ever get to that repro
