### ISSUE TITLE
Exception when project doesn't output symbols file.

### ISSUE THREAD

**Issue by distantcam** [Fody/Fody#333]
Originally reported in Fody/Costura#198, I have also confirmed this issue using Fody/Obsolete.

The issue occurs when the project build is set to not output any debug symbols. Using Fody 2.0.7.

```
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Operation is not valid due to the current state of the object.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
1>MSBUILD : error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
1>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>MSBUILD : error :    at InnerWeaver.ReadModule() in C:\projects\fody\FodyIsolated\ModuleReader.cs:line 32
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
1>MSBUILD : error : Source:
1>MSBUILD : error : Mono.Cecil
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ReadSymbols(Mono.Cecil.Cil.ISymbolReader)
1>MSBUILD : error : 
```

**Comment by distantcam** [comment]
More info. I can only reproduce the problem when I change the debug symbols setting to `none` after previously having it on. Visual Studio isn't cleaning up the symbol file during the build, so the stale file is still there, and when Fody tries to load the new assembly with the stale symbol file this error occurs.

For now the simple workaround is to clean the build after the setting is changed.
