### ISSUE TITLE
Solution fails to build due to Fody. Cleaning the SLN will fixes it though. 

### ISSUE THREAD

**Issue by Pangamma** [Fody/Fody#389]
Goes away if I clean the solution then rebuild. I've run into this issue a good 50 times tonight though. It is getting annoying to the point of me wanting to temporarily uninstall Fody. Please fix? 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Exception from HRESULT: 0x806D0004
StackTrace:
   at Mono.Cecil.Pdb.ISymUnmanagedWriter2.Initialize(Object emitter, String filename, IStream pIStream, Boolean fFullBuild)
   at Mono.Cecil.Pdb.NativePdbWriterProvider.CreateWriter(ModuleDefinition module, String pdb)
   at Mono.Cecil.Pdb.NativePdbWriterProvider.GetSymbolWriter(ModuleDefinition module, String fileName)
   at Mono.Cecil.Pdb.PdbWriterProvider.GetSymbolWriter(ModuleDefinition module, String fileName)
   at Mono.Cecil.ModuleWriter.GetSymbolWriter(ModuleDefinition module, String fq_name, ISymbolWriterProvider symbol_writer_provider, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 18
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 89
Source:
Mono.Cecil.Pdb
TargetSite:
Void Initialize(System.Object, System.String, System.Runtime.InteropServices.ComTypes.IStream, Boolean)	MegaPixels	

Severity	Code	Description	Project	File	Line	Suppression State
Error	Metadata	Error while reading 'C:\Users\prota\Dropbox\Rhodesia\Projects\OTHER\Tools\MegaPixels\MegaPixels\obj\Debug\MegaPixels.exe': PE image doesn't contain managed metadata.	MegaPixels		1	Active

**Comment by SimonCropp** [comment]
What version r u using?

**Comment by Pangamma** [comment]
@SimonCropp v1.6.2 for Costura.Fody
2=v2.1.2 for Fody.

**Comment by SimonCropp** [comment]
sorry i have no idea ho to proceed with this. the next time i happens raise an issue in mono cecil and include the dll from the obj dir
