### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by ezioi** [Fody/Fody#399]
When i compile in Release mode i got this error:

Error	1	Fody: An unhandled exception occurred:
Exception:
Exception of type 'System.OutOfMemoryException' was thrown.
StackTrace:
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ModuleWeaver.CalculateHash() in c:\TeamCity\buildAgent\work\c596b706194e070d\Fody\HashCalculator.cs:line 13
   at ModuleWeaver.Execute() in c:\TeamCity\buildAgent\work\c596b706194e070d\Fody\ModuleWeaver.cs:line 33
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
   at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
Source:
System.Core
TargetSite:
Void .ctor(System.Collections.Generic.IEnumerable`1[TElement])
	MyPos

**Comment by SimonCropp** [comment]
can u upload a repro
