### ISSUE TITLE
Changes in Cecil makes AssemblyDefinition disposable

### ISSUE THREAD

**Issue by joj** [Fody/Fody#420]
In the latest Cecil there was a semi-breaking change that I'm seeing in at least one location in PropertyChanged (https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/MsCoreReferenceFinder.cs#L25). AssemblyDefinition is now IDisposable and not disposing it will lock the assemblies that are inspected until the build ends. This may conflict with other parts of the build doing inspection or in VS it may even lock after the fact if the msbuild process lingers. There's two solutions: there's an InMemory option that keeps the old behavior, or the assembly definitions need to be disposed after being used. I think the later is better. I know of that usage I posted there, but there may be others in other weavers.

**Comment by SimonCropp** [comment]
isnt this scenario handled by this code? https://github.com/Fody/Fody/blob/master/FodyIsolated/AssemblyResolver.cs#L112

**Comment by SimonCropp** [comment]
could u perhaps upload a small repro for me to investigate further?

**Comment by joj** [comment]
I need to go through the code to understand if that's enough. We had a bug reported on our side were second builds would hang because of locked dlls. Removing PropertyChanged "fixed" the bug. I'll try to get the repro from that.

**Comment by joj** [comment]
I have a repro. Uploading now. The basics are: I have a console app with 2 .NetStandard libraries. One of them uses Fody, the other doesn't. I build, and everything works. Then I change something on the library using Fody (ClassLibrary2 in my sample) and I get this:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
The process cannot access the file 'C:\Users\joaqu\source\repos\ConsoleApp3\ClassLibrary2\obj\Debug\netstandard2.0\ClassLibrary2.dll' because it is being used by another process.
StackTrace:
Server stack trace: 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at IsolatedContainsTypeChecker.Check(String assemblyPath, String typeName) in C:\projects\fody\FodyIsolated\IsolatedContainsTypeChecker.cs:line 20
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IContainsTypeChecker.Check(String assemblyPath, String typeName)
   at ContainsTypeChecker.Check(String assemblyPath, String typeName) in C:\projects\fody\Fody\ContainsTypeChecker.cs:line 28
   at Processor.ShouldStartSinceFileChanged() in C:\projects\fody\Fody\FileChangedChecker.cs:line 6
   at Processor.Inner() in C:\projects\fody\Fody\Processor.cs:line 68
   at Processor.Execute() in C:\projects\fody\Fody\Processor.cs:line 46
Source:
mscorlib
TargetSite:
Void WinIOError(Int32, System.String)
	ClassLibrary2		1	

I'll comment again once I uploaded with the source of the repro.

**Comment by joj** [comment]
@SimonCropp pushed here: https://github.com/joj/ConsoleSample

To repro, build and then change the property Name in ClassLibrary2.Model to something else (whatever) and try to compile or run. You'll get the exception in the previous comment.

**Comment by SimonCropp** [comment]
still not failing for me :(

but that sample is using an out of date version of fody. can u update to  2.2 and try again

**Comment by joj** [comment]
The good news is that I don't have a repro with 2.2. The thing is I didn't install Fody at all, just PropertyChanged. The dependency was pulled magically with the new PackageReferences thing in nuget/.NetStandard, so maybe the problem is just that for some reason that other nuget is pulling in an old Fody.

**Comment by SimonCropp** [comment]
yeah nuget defaults to the oldest and most buggy version of any reference. i have spoken to them about it. it is "by design"

so shall we close this?

**Comment by joj** [comment]
Yeah, sure. I'll let our support now that the super simple workaround is to manually install Fody to the latest version.

**Comment by SimonCropp** [comment]
just an fyi u could also potentially use wildcards

```

  <ItemGroup>
    <PackageReference Include="PropertyChanged.Fody" Version="2.*"/>
    <PackageReference Include="Fody" Version="2.*"/>
  </ItemGroup>
```

**Comment by joj** [comment]
Yeah, what worries me is that most users will experience the default behavior in VS, and the default behavior feels broken even if it isn't. A possibility for avoiding this would be to make the weavers require 2.2.0 as a minimum, instead of 2.0.0.

**Comment by SimonCropp** [comment]
> A possibility for avoiding this would be to make the weavers require 2.2.0 as a minimum, instead of 2.0.0.

this is true. but the end result would be: on every fody release all downstreams would need to release a new nuget to update their min version.

I dont think that is viable

**Comment by tom-englert** [comment]
@SimonCropp yes, forcing new releases would be too much overhead, however if a new version of any weaver is released anyhow, it should be update to require the latest version of Fody.

**Comment by SimonCropp** [comment]
>  however if a new version of any weaver is released anyhow, it should be update to require the latest version of Fody

yeah that is fair and i will try to be more diligent in doing that
