### ISSUE TITLE
Exception when upgrading from 2.3.23 to 2.3.24

### ISSUE THREAD

**Issue by tom-englert** [Fody/Fody#481]
After upgrading from 2.3.23 to 2.3.24 I get this exception during build:
```
  Fody:   Scanning package directory: 'C:\Users\Thomas\.nuget\packages\propertychanged.fody\2.1.4'
  Fody:     Fody weaver file added 'C:\Users\Thomas\.nuget\packages\propertychanged.fody\2.1.4\PropertyChanged.Fody.dll'
  Fody:   Scanning package directory: 'D:\Develop\My Open Source\GitHub\AutoProperties.Fody\source\TestLibrary\AutoProperties\AutoProperties.csproj'
MSBUILD : error : Fody: An unhandled exception occurred:
MSBUILD : error : Exception:
MSBUILD : error : Could not find a part of the path 'D:\Develop\My Open Source\GitHub\AutoProperties.Fody\source\TestLibrary\AutoProperties\AutoProperties.csproj'.
MSBUILD : error : Type:
MSBUILD : error : System.IO.DirectoryNotFoundException
MSBUILD : error : StackTrace:
MSBUILD : error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
MSBUILD : error :    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
MSBUILD : error :    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
MSBUILD : error :    at System.IO.Directory.GetFiles(String path)
MSBUILD : error :    at AddinFinder.GetAssemblyFromDir(String dir, String packageName)
MSBUILD : error :    at AddinFinder.FindAddinDirectories()
MSBUILD : error :    at Processor.FindWeavers()
MSBUILD : error :    at Processor.Inner()
MSBUILD : error :    at Processor.Execute()
SBUILD : error :
```
The error is reported in the TestLibrary project. 
However this project only uses the PropertyChanged weaver and has no reference to the AutoProperties project.

The AutoProperties project is in `'D:\Develop\My Open Source\GitHub\AutoProperties.Fody\source\AutoProperties\AutoProperties.csproj`, and not in a sub directory of the TestLibrary project.

If I unload all projects except the `TestLibrary` project, it builds fine. If I then reload just the `AutoProperties` project, the build fails.

To reproduce this, use https://github.com/tom-englert/AutoProperties.Fody/tree/Try_24

**Comment by tom-englert** [comment]
P.S. this does not happen if I use the "old style" projects:
https://github.com/tom-englert/AutoProperties.Fody/tree/Try_24oldStyle

**Comment by SimonCropp** [comment]
fix should now be deployed
