### ISSUE TITLE
Still getting these Fody `System.IO.PathTooLongException` together with Fody.Costura

### ISSUE THREAD

**Issue by punker76** [Fody/Fody#482]
Odd to see, that the path is limited.

*Fody 2.3.24*
*Costura.Fody 1.6.2*

I put all my sources normally under `c:\Users\<USER>\Documents\Git\`. So the only workaround with the current Fody is, not to work with current Fody.

```
Error		Fody: An unhandled exception occurred:
Exception:
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Type:
System.IO.PathTooLongException
StackTrace:
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ModuleWeaver.Embed(String prefix, String fullPath, Boolean compress) in C:\projects\costura\src\Costura\ResourceEmbedder.cs:line 204
   at ModuleWeaver.EmbedResources(Configuration config) in C:\projects\costura\src\Costura\ResourceEmbedder.cs:line 39
   at ModuleWeaver.Execute() in C:\projects\costura\src\Costura\ModuleWeaver.cs:line 33
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 200
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 102
Source:
mscorlib
TargetSite:
System.String Normalize(System.String, UInt32, Boolean, Boolean)	MahApps.Metro.Caliburn.Demo.NET40			
```

- [x] 👉  https://opencollective.com/fody/donate

**Comment by SimonCropp** [comment]
U closed this after opening. Did u resolve it in some way?

**Comment by punker76** [comment]
@SimonCropp Yes, cause I think this is more related to the `Costura` plugin https://github.com/Fody/Costura/issues/216#issuecomment-362904129
