### ISSUE TITLE
Fody InSolutionWeaving does not work with ProduceReferenceAssembly

### ISSUE THREAD

**Issue by 0x53A** [Fody/Fody#491]
With ``<ProduceReferenceAssembly>true</ProduceReferenceAssembly>`` (see https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md), Fody fails with

```
2>------ Rebuild All started: Project: UseTheWeaver, Configuration: Debug Any CPU ------
2>    Fody: Fody (version 2.4.4.0) Executing
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Cannot load a reference assembly for execution.
2>MSBUILD : error : Type:
2>MSBUILD : error : System.BadImageFormatException
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
2>MSBUILD : error :    at System.Reflection.Assembly.Load(Byte[] rawAssembly)
2>MSBUILD : error :    at InnerWeaver.LoadFromFile(String assemblyPath)
2>MSBUILD : error :    at InnerWeaver.LoadAssembly(String assemblyPath)
2>MSBUILD : error :    at InnerWeaver.InitialiseWeavers()
2>MSBUILD : error :    at InnerWeaver.Execute()
2>MSBUILD : error : Source:
2>MSBUILD : error : mscorlib
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : System.Reflection.RuntimeAssembly nLoadImage(Byte[], Byte[], System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean, System.Security.SecurityContextSource)
2>MSBUILD : error : 
2>    Fody:   Finished Fody 116ms.
```

### Proposed fix:

ReferenceAssemblies have a special Attribute: ``System.Runtime.CompilerServices.ReferenceAssemblyAttribute``.

Extend the dll loader logic to skip all assemblies with that attribute.

-----------------

Complete as many of the following as possible

 * [x] Uploaded a minimal solution that reproduces the problem with the fewest moving pieces. Preferably a public GitHub repository: https://github.com/0x53A/FodyCustomWeaverAndRefAssemblies
 * [ ] Submitted a PR (https://help.github.com/articles/about-pull-requests/) with a failing unit test.
 * [x] Submitted a PR (https://help.github.com/articles/about-pull-requests/) with a fix: https://github.com/Fody/Fody/pull/492

**Comment by 0x53A** [comment]
The unit test fails because [Weavers.dll](https://github.com/Fody/Fody/blob/master/Tests/Fody/WeaversProjectFileFinder/WithWeaver/Weavers/bin/Debug/Weavers.dll) is actually a html file...
