### ISSUE TITLE
The "Fody.WeavingTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by krk** [Fody/Fody#87]
We have the following error on some build servers.

```
The "Fody.WeavingTask" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'FodyIsolated' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
   at ContainsTypeChecker..cctor() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\ContainsTypeChecker.cs:line 14
```

**Comment by SamuelDebruyn** [comment]
@SimonCropp My code is also on a network drive and I'm not getting the exception you mentioned. This is what I get:

```
2>  C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018: The "Fody.WeavingTask" task failed unexpectedly.
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018: 
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents)
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at Fody.WeavingTask.Execute()
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Users\Sam\.nuget\packages\fody\3.3.2\build\Fody.targets(31,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by ltrzesniewski** [comment]
It's not exactly surprising you're not getting the same exception 4 years later... The code changed quite a bit in the meantime.

In your case it looks like it fails to write a cache file (the `IntermediateCopyLocalFilesCache`).

Try v3.2.10, see if it works.

**Comment by ltrzesniewski** [comment]
I just tried to build a test project from a network drive, and it worked fine for me, both from VS and the command line.
